service: hugo-cms
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  httpApi:
    cors: true
    authorizers:
      accessTokenAuth0: # define external jwt authorizer via the SaaS Plattform auth0
        identitySource: $request.header.Authorization
        issuerUrl: https://localleon.eu.auth0.com/
        audience:
          - https://85tpt5asaa.execute-api.eu-central-1.amazonaws.com
package:
  patterns:
    - "!.venv/**"
    - "!.git/**"
    - "!__pycache__/**" # for python 3.x
    - "!node_modules/**"

functions:
  main:
    handler: handler.main_handler
    events:
      - httpApi:
          path: /upload
          method: post
          authorizer:
            name: accessTokenAuth0

      - httpApi:
          path: /list
          method: get
          authorizer:
            name: accessTokenAuth0

      - httpApi:
          path: /delete/{key}
          method: DELETE
          authorizer:
            name: accessTokenAuth0

      - httpApi:
          path: /get/{key}
          method: GET
          authorizer:
            name: accessTokenAuth0

plugins:
  - serverless-python-requirements
