service: hugo-cms
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1

functions:
  main:
    handler: handler.main_handler
    events:
      - httpApi:
          path: /upload
          method: post
      - httpApi:
          path: /list
          method: get
      - httpApi:
          path: /delete
          method: DELETE

plugins:
  - serverless-python-requirements
