name: Unit Tests (pyTest)
on: [push]

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: UTC

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set Backend Directory & install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install -r requirements-dev.txt

      - name: Test with pytest
        run: |
          pwd 
          pytest -v
